//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fritz.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_COM_PORT {
            get {
                return ((string)(this["Last_COM_PORT"]));
            }
            set {
                this["Last_COM_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_X_Axis {
            get {
                return ((string)(this["Joystick_X_Axis"]));
            }
            set {
                this["Joystick_X_Axis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_Y_Axis {
            get {
                return ((string)(this["Joystick_Y_Axis"]));
            }
            set {
                this["Joystick_Y_Axis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_Twist {
            get {
                return ((string)(this["Joystick_Twist"]));
            }
            set {
                this["Joystick_Twist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_Rudder {
            get {
                return ((string)(this["Joystick_Rudder"]));
            }
            set {
                this["Joystick_Rudder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_Rotation {
            get {
                return ((string)(this["Joystick_Rotation"]));
            }
            set {
                this["Joystick_Rotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_Throttle {
            get {
                return ((string)(this["Joystick_Throttle"]));
            }
            set {
                this["Joystick_Throttle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_button_0 {
            get {
                return ((string)(this["Joystick_button_0"]));
            }
            set {
                this["Joystick_button_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_button_1 {
            get {
                return ((string)(this["Joystick_button_1"]));
            }
            set {
                this["Joystick_button_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_button_2 {
            get {
                return ((string)(this["Joystick_button_2"]));
            }
            set {
                this["Joystick_button_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_button_3 {
            get {
                return ((string)(this["Joystick_button_3"]));
            }
            set {
                this["Joystick_button_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_button_4 {
            get {
                return ((string)(this["Joystick_button_4"]));
            }
            set {
                this["Joystick_button_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_button_5 {
            get {
                return ((string)(this["Joystick_button_5"]));
            }
            set {
                this["Joystick_button_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_button_6 {
            get {
                return ((string)(this["Joystick_button_6"]));
            }
            set {
                this["Joystick_button_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_button_7 {
            get {
                return ((string)(this["Joystick_button_7"]));
            }
            set {
                this["Joystick_button_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_button_8 {
            get {
                return ((string)(this["Joystick_button_8"]));
            }
            set {
                this["Joystick_button_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_button_9 {
            get {
                return ((string)(this["Joystick_button_9"]));
            }
            set {
                this["Joystick_button_9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_button_10 {
            get {
                return ((string)(this["Joystick_button_10"]));
            }
            set {
                this["Joystick_button_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_button_11 {
            get {
                return ((string)(this["Joystick_button_11"]));
            }
            set {
                this["Joystick_button_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Joystick_button_12 {
            get {
                return ((string)(this["Joystick_button_12"]));
            }
            set {
                this["Joystick_button_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_X_Axis_Invert {
            get {
                return ((bool)(this["Joystick_X_Axis_Invert"]));
            }
            set {
                this["Joystick_X_Axis_Invert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_Y_Axis_Invert {
            get {
                return ((bool)(this["Joystick_Y_Axis_Invert"]));
            }
            set {
                this["Joystick_Y_Axis_Invert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_Twist_Invert {
            get {
                return ((bool)(this["Joystick_Twist_Invert"]));
            }
            set {
                this["Joystick_Twist_Invert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_Rudder_Invert {
            get {
                return ((bool)(this["Joystick_Rudder_Invert"]));
            }
            set {
                this["Joystick_Rudder_Invert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_Rotation_Invert {
            get {
                return ((bool)(this["Joystick_Rotation_Invert"]));
            }
            set {
                this["Joystick_Rotation_Invert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_Throttle_Invert {
            get {
                return ((bool)(this["Joystick_Throttle_Invert"]));
            }
            set {
                this["Joystick_Throttle_Invert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Joystick_button_0_Revert {
            get {
                return ((bool)(this["Joystick_button_0_Revert"]));
            }
            set {
                this["Joystick_button_0_Revert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Joystick_button_1_Revert {
            get {
                return ((bool)(this["Joystick_button_1_Revert"]));
            }
            set {
                this["Joystick_button_1_Revert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_button_2_Revert {
            get {
                return ((bool)(this["Joystick_button_2_Revert"]));
            }
            set {
                this["Joystick_button_2_Revert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_button_3_Revert {
            get {
                return ((bool)(this["Joystick_button_3_Revert"]));
            }
            set {
                this["Joystick_button_3_Revert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_button_4_Revert {
            get {
                return ((bool)(this["Joystick_button_4_Revert"]));
            }
            set {
                this["Joystick_button_4_Revert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_button_5_Revert {
            get {
                return ((bool)(this["Joystick_button_5_Revert"]));
            }
            set {
                this["Joystick_button_5_Revert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_button_6_Revert {
            get {
                return ((bool)(this["Joystick_button_6_Revert"]));
            }
            set {
                this["Joystick_button_6_Revert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_button_7_Revert {
            get {
                return ((bool)(this["Joystick_button_7_Revert"]));
            }
            set {
                this["Joystick_button_7_Revert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_button_8_Revert {
            get {
                return ((bool)(this["Joystick_button_8_Revert"]));
            }
            set {
                this["Joystick_button_8_Revert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_button_9_Revert {
            get {
                return ((bool)(this["Joystick_button_9_Revert"]));
            }
            set {
                this["Joystick_button_9_Revert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_button_10_Revert {
            get {
                return ((bool)(this["Joystick_button_10_Revert"]));
            }
            set {
                this["Joystick_button_10_Revert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_button_11_Revert {
            get {
                return ((bool)(this["Joystick_button_11_Revert"]));
            }
            set {
                this["Joystick_button_11_Revert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Joystick_button_12_Revert {
            get {
                return ((bool)(this["Joystick_button_12_Revert"]));
            }
            set {
                this["Joystick_button_12_Revert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_1 {
            get {
                return ((string)(this["Keyboard_Key_1"]));
            }
            set {
                this["Keyboard_Key_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_2 {
            get {
                return ((string)(this["Keyboard_Key_2"]));
            }
            set {
                this["Keyboard_Key_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_3 {
            get {
                return ((string)(this["Keyboard_Key_3"]));
            }
            set {
                this["Keyboard_Key_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_4 {
            get {
                return ((string)(this["Keyboard_Key_4"]));
            }
            set {
                this["Keyboard_Key_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_5 {
            get {
                return ((string)(this["Keyboard_Key_5"]));
            }
            set {
                this["Keyboard_Key_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_6 {
            get {
                return ((string)(this["Keyboard_Key_6"]));
            }
            set {
                this["Keyboard_Key_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_7 {
            get {
                return ((string)(this["Keyboard_Key_7"]));
            }
            set {
                this["Keyboard_Key_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_8 {
            get {
                return ((string)(this["Keyboard_Key_8"]));
            }
            set {
                this["Keyboard_Key_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_9 {
            get {
                return ((string)(this["Keyboard_Key_9"]));
            }
            set {
                this["Keyboard_Key_9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_10 {
            get {
                return ((string)(this["Keyboard_Key_10"]));
            }
            set {
                this["Keyboard_Key_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_11 {
            get {
                return ((string)(this["Keyboard_Key_11"]));
            }
            set {
                this["Keyboard_Key_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_12 {
            get {
                return ((string)(this["Keyboard_Key_12"]));
            }
            set {
                this["Keyboard_Key_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_13 {
            get {
                return ((string)(this["Keyboard_Key_13"]));
            }
            set {
                this["Keyboard_Key_13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_14 {
            get {
                return ((string)(this["Keyboard_Key_14"]));
            }
            set {
                this["Keyboard_Key_14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Key_15 {
            get {
                return ((string)(this["Keyboard_Key_15"]));
            }
            set {
                this["Keyboard_Key_15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Keyboard_Revert_1 {
            get {
                return ((bool)(this["Keyboard_Revert_1"]));
            }
            set {
                this["Keyboard_Revert_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("131072")]
        public int Keyboard_Modifiers_1 {
            get {
                return ((int)(this["Keyboard_Modifiers_1"]));
            }
            set {
                this["Keyboard_Modifiers_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_1 {
            get {
                return ((string)(this["Keyboard_Action_1"]));
            }
            set {
                this["Keyboard_Action_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Keyboard_Revert_2 {
            get {
                return ((bool)(this["Keyboard_Revert_2"]));
            }
            set {
                this["Keyboard_Revert_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Keyboard_Revert_3 {
            get {
                return ((bool)(this["Keyboard_Revert_3"]));
            }
            set {
                this["Keyboard_Revert_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Keyboard_Revert_4 {
            get {
                return ((bool)(this["Keyboard_Revert_4"]));
            }
            set {
                this["Keyboard_Revert_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Keyboard_Revert_5 {
            get {
                return ((bool)(this["Keyboard_Revert_5"]));
            }
            set {
                this["Keyboard_Revert_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Keyboard_Revert_6 {
            get {
                return ((bool)(this["Keyboard_Revert_6"]));
            }
            set {
                this["Keyboard_Revert_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Keyboard_Revert_7 {
            get {
                return ((bool)(this["Keyboard_Revert_7"]));
            }
            set {
                this["Keyboard_Revert_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Keyboard_Revert_8 {
            get {
                return ((bool)(this["Keyboard_Revert_8"]));
            }
            set {
                this["Keyboard_Revert_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Keyboard_Revert_9 {
            get {
                return ((bool)(this["Keyboard_Revert_9"]));
            }
            set {
                this["Keyboard_Revert_9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Keyboard_Revert_10 {
            get {
                return ((bool)(this["Keyboard_Revert_10"]));
            }
            set {
                this["Keyboard_Revert_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Keyboard_Revert_11 {
            get {
                return ((bool)(this["Keyboard_Revert_11"]));
            }
            set {
                this["Keyboard_Revert_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Keyboard_Revert_12 {
            get {
                return ((bool)(this["Keyboard_Revert_12"]));
            }
            set {
                this["Keyboard_Revert_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Keyboard_Revert_13 {
            get {
                return ((bool)(this["Keyboard_Revert_13"]));
            }
            set {
                this["Keyboard_Revert_13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Keyboard_Revert_14 {
            get {
                return ((bool)(this["Keyboard_Revert_14"]));
            }
            set {
                this["Keyboard_Revert_14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Keyboard_Revert_15 {
            get {
                return ((bool)(this["Keyboard_Revert_15"]));
            }
            set {
                this["Keyboard_Revert_15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("131072")]
        public int Keyboard_Modifiers_2 {
            get {
                return ((int)(this["Keyboard_Modifiers_2"]));
            }
            set {
                this["Keyboard_Modifiers_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("131072")]
        public int Keyboard_Modifiers_3 {
            get {
                return ((int)(this["Keyboard_Modifiers_3"]));
            }
            set {
                this["Keyboard_Modifiers_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("131072")]
        public int Keyboard_Modifiers_4 {
            get {
                return ((int)(this["Keyboard_Modifiers_4"]));
            }
            set {
                this["Keyboard_Modifiers_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("131072")]
        public int Keyboard_Modifiers_5 {
            get {
                return ((int)(this["Keyboard_Modifiers_5"]));
            }
            set {
                this["Keyboard_Modifiers_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("262144")]
        public int Keyboard_Modifiers_6 {
            get {
                return ((int)(this["Keyboard_Modifiers_6"]));
            }
            set {
                this["Keyboard_Modifiers_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("262144")]
        public int Keyboard_Modifiers_7 {
            get {
                return ((int)(this["Keyboard_Modifiers_7"]));
            }
            set {
                this["Keyboard_Modifiers_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("262144")]
        public int Keyboard_Modifiers_8 {
            get {
                return ((int)(this["Keyboard_Modifiers_8"]));
            }
            set {
                this["Keyboard_Modifiers_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("262144")]
        public int Keyboard_Modifiers_9 {
            get {
                return ((int)(this["Keyboard_Modifiers_9"]));
            }
            set {
                this["Keyboard_Modifiers_9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("327680")]
        public int Keyboard_Modifiers_10 {
            get {
                return ((int)(this["Keyboard_Modifiers_10"]));
            }
            set {
                this["Keyboard_Modifiers_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("327680")]
        public int Keyboard_Modifiers_11 {
            get {
                return ((int)(this["Keyboard_Modifiers_11"]));
            }
            set {
                this["Keyboard_Modifiers_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Keyboard_Modifiers_12 {
            get {
                return ((int)(this["Keyboard_Modifiers_12"]));
            }
            set {
                this["Keyboard_Modifiers_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Keyboard_Modifiers_13 {
            get {
                return ((int)(this["Keyboard_Modifiers_13"]));
            }
            set {
                this["Keyboard_Modifiers_13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Keyboard_Modifiers_14 {
            get {
                return ((int)(this["Keyboard_Modifiers_14"]));
            }
            set {
                this["Keyboard_Modifiers_14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Keyboard_Modifiers_15 {
            get {
                return ((int)(this["Keyboard_Modifiers_15"]));
            }
            set {
                this["Keyboard_Modifiers_15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_2 {
            get {
                return ((string)(this["Keyboard_Action_2"]));
            }
            set {
                this["Keyboard_Action_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_3 {
            get {
                return ((string)(this["Keyboard_Action_3"]));
            }
            set {
                this["Keyboard_Action_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_4 {
            get {
                return ((string)(this["Keyboard_Action_4"]));
            }
            set {
                this["Keyboard_Action_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_5 {
            get {
                return ((string)(this["Keyboard_Action_5"]));
            }
            set {
                this["Keyboard_Action_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_6 {
            get {
                return ((string)(this["Keyboard_Action_6"]));
            }
            set {
                this["Keyboard_Action_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_7 {
            get {
                return ((string)(this["Keyboard_Action_7"]));
            }
            set {
                this["Keyboard_Action_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_8 {
            get {
                return ((string)(this["Keyboard_Action_8"]));
            }
            set {
                this["Keyboard_Action_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_9 {
            get {
                return ((string)(this["Keyboard_Action_9"]));
            }
            set {
                this["Keyboard_Action_9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_10 {
            get {
                return ((string)(this["Keyboard_Action_10"]));
            }
            set {
                this["Keyboard_Action_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_11 {
            get {
                return ((string)(this["Keyboard_Action_11"]));
            }
            set {
                this["Keyboard_Action_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_12 {
            get {
                return ((string)(this["Keyboard_Action_12"]));
            }
            set {
                this["Keyboard_Action_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_13 {
            get {
                return ((string)(this["Keyboard_Action_13"]));
            }
            set {
                this["Keyboard_Action_13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_14 {
            get {
                return ((string)(this["Keyboard_Action_14"]));
            }
            set {
                this["Keyboard_Action_14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Keyboard_Action_15 {
            get {
                return ((string)(this["Keyboard_Action_15"]));
            }
            set {
                this["Keyboard_Action_15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Trigger_Enabled {
            get {
                return ((bool)(this["Trigger_Enabled"]));
            }
            set {
                this["Trigger_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Trigger_Check_Sonar {
            get {
                return ((bool)(this["Trigger_Check_Sonar"]));
            }
            set {
                this["Trigger_Check_Sonar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Trigger_Check_IR {
            get {
                return ((bool)(this["Trigger_Check_IR"]));
            }
            set {
                this["Trigger_Check_IR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Trigger_Distance {
            get {
                return ((int)(this["Trigger_Distance"]));
            }
            set {
                this["Trigger_Distance"] = value;
            }
        }
    }
}
